# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスへのコメントがなくても許す
Documentation:
  Enabled: false

# ファイル末尾の改行を許可
TrailingBlankLines:
  EnforcedStyle: final_blank_line

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'

inherit_from: .rubocop_todo.yml

